# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/handwriting.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/handwriting.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18protos/handwriting.proto\"4\n\rStrokeFeature\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05penup\x18\x03 \x01(\x08\"*\n\x06Stroke\x12 \n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x0e.StrokeFeature\"\x18\n\x05Label\x12\x0f\n\x07indices\x18\x01 \x03(\x03\"8\n\x06Sample\x12\x17\n\x06stroke\x18\x01 \x01(\x0b\x32\x07.Stroke\x12\x15\n\x05label\x18\x02 \x01(\x0b\x32\x06.Labelb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STROKEFEATURE = _descriptor.Descriptor(
  name='StrokeFeature',
  full_name='StrokeFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='StrokeFeature.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='StrokeFeature.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='penup', full_name='StrokeFeature.penup', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=80,
)


_STROKE = _descriptor.Descriptor(
  name='Stroke',
  full_name='Stroke',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='Stroke.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=124,
)


_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='indices', full_name='Label.indices', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=150,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stroke', full_name='Sample.stroke', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='Sample.label', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=208,
)

_STROKE.fields_by_name['features'].message_type = _STROKEFEATURE
_SAMPLE.fields_by_name['stroke'].message_type = _STROKE
_SAMPLE.fields_by_name['label'].message_type = _LABEL
DESCRIPTOR.message_types_by_name['StrokeFeature'] = _STROKEFEATURE
DESCRIPTOR.message_types_by_name['Stroke'] = _STROKE
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE

StrokeFeature = _reflection.GeneratedProtocolMessageType('StrokeFeature', (_message.Message,), dict(
  DESCRIPTOR = _STROKEFEATURE,
  __module__ = 'protos.handwriting_pb2'
  # @@protoc_insertion_point(class_scope:StrokeFeature)
  ))
_sym_db.RegisterMessage(StrokeFeature)

Stroke = _reflection.GeneratedProtocolMessageType('Stroke', (_message.Message,), dict(
  DESCRIPTOR = _STROKE,
  __module__ = 'protos.handwriting_pb2'
  # @@protoc_insertion_point(class_scope:Stroke)
  ))
_sym_db.RegisterMessage(Stroke)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'protos.handwriting_pb2'
  # @@protoc_insertion_point(class_scope:Label)
  ))
_sym_db.RegisterMessage(Label)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'protos.handwriting_pb2'
  # @@protoc_insertion_point(class_scope:Sample)
  ))
_sym_db.RegisterMessage(Sample)


# @@protoc_insertion_point(module_scope)
